project_id = "jehgvrskdyijirecznii"

[functions.scrape-products]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.update-products]
verify_jwt = false

[functions.complete-professional-signup]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.check-professional-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.create-session-payment]
verify_jwt = false

[functions.generate-carousel-image]
verify_jwt = false

[functions.fix-existing-news]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.create-mercadopago-subscription]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.get-mercadopago-public-key]
verify_jwt = false

[functions.process-mercadopago-payment]
verify_jwt = false
