project_id = "jehgvrskdyijirecznii"

[functions.scrape-products]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.update-products]
verify_jwt = false

[functions.complete-professional-signup]
verify_jwt = false
