import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// ============================================================
// Native VAPID JWT signing using Deno crypto (fixes BadJwtToken on Apple)
// ============================================================

function base64UrlEncode(data: ArrayBuffer | Uint8Array): string {
  const bytes = data instanceof Uint8Array ? data : new Uint8Array(data);
  let str = "";
  for (const b of bytes) str += String.fromCharCode(b);
  return btoa(str).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function base64UrlDecode(str: string): Uint8Array {
  const padded = str.replace(/-/g, "+").replace(/_/g, "/");
  const padding = (4 - (padded.length % 4)) % 4;
  const raw = atob(padded + "=".repeat(padding));
  return Uint8Array.from([...raw].map((c) => c.charCodeAt(0)));
}

async function buildVapidJWT(audience: string, subject: string, privateKeyB64: string): Promise<string> {
  const now = Math.floor(Date.now() / 1000);
  const header = { typ: "JWT", alg: "ES256" };
  const payload = { aud: audience, exp: now + 43200, sub: subject };

  const encodedHeader = base64UrlEncode(new TextEncoder().encode(JSON.stringify(header)));
  const encodedPayload = base64UrlEncode(new TextEncoder().encode(JSON.stringify(payload)));
  const signingInput = `${encodedHeader}.${encodedPayload}`;

  // Import private key (VAPID keys are raw base64url-encoded P-256 private keys)
  const rawPrivKey = base64UrlDecode(privateKeyB64);

  const cryptoKey = await crypto.subtle.importKey(
    "pkcs8",
    rawPrivKey,
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["sign"]
  ).catch(async () => {
    // If not pkcs8, try as raw scalar (32 bytes) → wrap in JWK
    const jwk = {
      kty: "EC",
      crv: "P-256",
      d: privateKeyB64,
      // x and y are not strictly needed for signing import via JWK in some runtimes
      // but Deno requires them. Derive from private key is complex; use a different approach.
    };
    // Fallback: treat as PKCS8 DER that was base64url encoded
    return crypto.subtle.importKey(
      "raw",
      rawPrivKey,
      { name: "ECDSA", namedCurve: "P-256" },
      false,
      ["sign"]
    );
  });

  const signingData = new TextEncoder().encode(signingInput);
  const signature = await crypto.subtle.sign({ name: "ECDSA", hash: "SHA-256" }, cryptoKey, signingData);

  return `${signingInput}.${base64UrlEncode(signature)}`;
}

async function importVapidPrivateKey(privateKeyB64: string): Promise<CryptoKey> {
  const raw = base64UrlDecode(privateKeyB64);

  // VAPID private keys generated by web-push are 32-byte raw EC scalar.
  // We need to wrap them in PKCS8 DER format for importKey("pkcs8").
  // PKCS8 DER prefix for P-256 private key (ECPrivateKey wrapped in PrivateKeyInfo):
  // 30 41 02 01 00 30 13 06 07 2a 86 48 ce 3d 02 01 06 08 2a 86 48 ce 3d 03 01 07 04 27 30 25 02 01 01 04 20 <32 bytes key>
  const prefix = new Uint8Array([
    0x30, 0x41, 0x02, 0x01, 0x00, 0x30, 0x13, 0x06, 0x07,
    0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01, 0x06, 0x08,
    0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x04,
    0x27, 0x30, 0x25, 0x02, 0x01, 0x01, 0x04, 0x20,
  ]);

  const pkcs8 = new Uint8Array(prefix.length + raw.length);
  pkcs8.set(prefix);
  pkcs8.set(raw, prefix.length);

  return crypto.subtle.importKey(
    "pkcs8",
    pkcs8,
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["sign"]
  );
}

async function signVapidJWT(audience: string, subject: string, privateKeyB64: string): Promise<string> {
  const now = Math.floor(Date.now() / 1000);
  const header = { typ: "JWT", alg: "ES256" };
  const payload = { aud: audience, exp: now + 43200, sub: subject };

  const encodedHeader = base64UrlEncode(new TextEncoder().encode(JSON.stringify(header)));
  const encodedPayload = base64UrlEncode(new TextEncoder().encode(JSON.stringify(payload)));
  const signingInput = `${encodedHeader}.${encodedPayload}`;

  const cryptoKey = await importVapidPrivateKey(privateKeyB64);
  const signingData = new TextEncoder().encode(signingInput);
  const signature = await crypto.subtle.sign({ name: "ECDSA", hash: "SHA-256" }, cryptoKey, signingData);

  return `${signingInput}.${base64UrlEncode(signature)}`;
}

// ============================================================
// Send a single push notification using native fetch (no web-push lib)
// ============================================================
async function sendWebPush(
  sub: { endpoint: string; p256dh: string; auth: string },
  payload: string,
  vapidPublic: string,
  vapidPrivate: string,
  vapidSubject: string
): Promise<{ ok: boolean; status: number; body?: string }> {
  const url = new URL(sub.endpoint);
  const audience = `${url.protocol}//${url.host}`;

  const jwt = await signVapidJWT(audience, vapidSubject, vapidPrivate);
  const vapidHeader = `vapid t=${jwt},k=${vapidPublic}`;

  // Encrypt the payload using RFC 8291 content encoding
  // For simplicity and correctness, we'll send unencrypted via urgency header
  // and rely on the browser's push service to handle it.
  // Actually we must encrypt. Let's use the encryption approach:
  const encrypted = await encryptPayload(payload, sub.p256dh, sub.auth);

  const res = await fetch(sub.endpoint, {
    method: "POST",
    headers: {
      "Authorization": vapidHeader,
      "Content-Type": "application/octet-stream",
      "Content-Encoding": "aes128gcm",
      "TTL": "86400",
      "Urgency": "normal",
    },
    body: encrypted,
  });

  const body = await res.text().catch(() => "");
  return { ok: res.ok, status: res.status, body };
}

// ============================================================
// RFC 8291 Payload Encryption (aes128gcm)
// ============================================================
async function encryptPayload(
  plaintext: string,
  clientPublicKeyB64: string,
  clientAuthB64: string
): Promise<Uint8Array> {
  const encoder = new TextEncoder();
  const plaintextBytes = encoder.encode(plaintext);

  // Decode client keys
  const clientPublicKey = base64UrlDecode(clientPublicKeyB64);
  const clientAuth = base64UrlDecode(clientAuthB64);

  // Generate server ephemeral EC key pair
  const serverKeyPair = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" },
    true,
    ["deriveBits"]
  );

  // Export server public key (uncompressed, 65 bytes)
  const serverPublicKeyBuffer = await crypto.subtle.exportKey("raw", serverKeyPair.publicKey);
  const serverPublicKey = new Uint8Array(serverPublicKeyBuffer);

  // Import client public key
  const clientKey = await crypto.subtle.importKey(
    "raw",
    clientPublicKey,
    { name: "ECDH", namedCurve: "P-256" },
    false,
    []
  );

  // ECDH shared secret
  const sharedSecretBuffer = await crypto.subtle.deriveBits(
    { name: "ECDH", public: clientKey },
    serverKeyPair.privateKey,
    256
  );
  const sharedSecret = new Uint8Array(sharedSecretBuffer);

  // Generate salt (16 bytes)
  const salt = crypto.getRandomValues(new Uint8Array(16));

  // HKDF for PRK using auth secret
  const prk = await hkdf(clientAuth, sharedSecret, concat(encoder.encode("WebPush: info\0"), clientPublicKey, serverPublicKey), 32);

  // HKDF for content encryption key and nonce
  const cek = await hkdf(salt, prk, encoder.encode("Content-Encoding: aes128gcm\0"), 16);
  const nonce = await hkdf(salt, prk, encoder.encode("Content-Encoding: nonce\0"), 12);

  // Import CEK
  const cekKey = await crypto.subtle.importKey("raw", cek, { name: "AES-GCM" }, false, ["encrypt"]);

  // Add padding: record size is 4096, padding delimiter is 0x02
  const paddedPlaintext = new Uint8Array(plaintextBytes.length + 1);
  paddedPlaintext.set(plaintextBytes);
  paddedPlaintext[plaintextBytes.length] = 0x02; // padding delimiter

  // Encrypt
  const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv: nonce }, cekKey, paddedPlaintext);

  // Build header: salt (16) + rs (4, big-endian) + idlen (1) + server public key (65)
  const recordSize = 4096;
  const header = new Uint8Array(16 + 4 + 1 + serverPublicKey.length);
  header.set(salt, 0);
  new DataView(header.buffer).setUint32(16, recordSize, false);
  header[20] = serverPublicKey.length;
  header.set(serverPublicKey, 21);

  return concat(header, new Uint8Array(ciphertext));
}

async function hkdf(salt: Uint8Array, ikm: Uint8Array, info: Uint8Array, length: number): Promise<Uint8Array> {
  const keyMaterial = await crypto.subtle.importKey("raw", ikm, { name: "HKDF" }, false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits(
    { name: "HKDF", hash: "SHA-256", salt, info },
    keyMaterial,
    length * 8
  );
  return new Uint8Array(bits);
}

function concat(...arrays: Uint8Array[]): Uint8Array {
  const total = arrays.reduce((acc, a) => acc + a.length, 0);
  const result = new Uint8Array(total);
  let offset = 0;
  for (const a of arrays) {
    result.set(a, offset);
    offset += a.length;
  }
  return result;
}

// ============================================================
// Edge Function handler
// ============================================================
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: corsHeaders });
    }

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const supabaseUser = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const token = authHeader.replace("Bearer ", "");
    const { data: claimsData } = await supabaseUser.auth.getClaims(token);
    if (!claimsData?.claims) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: corsHeaders });
    }

    const userId = claimsData.claims.sub;

    const { data: rolesData } = await supabaseAdmin
      .from("user_roles")
      .select("role")
      .eq("user_id", userId);

    const hasPermission = rolesData?.some((r) => ["admin", "developer"].includes(r.role));
    if (!hasPermission) {
      return new Response(JSON.stringify({ error: "Forbidden" }), { status: 403, headers: corsHeaders });
    }

    const body = await req.json();
    const { title, message, type = "info", link, target_user_id, target_club_id, icon } = body;

    if (!title || !message) {
      return new Response(
        JSON.stringify({ error: "title and message are required" }),
        { status: 400, headers: corsHeaders }
      );
    }

    // Determine target user IDs
    let userIds: string[] = [];

    if (target_user_id) {
      userIds = [target_user_id.trim()];
      console.log(`Targeting specific user: ${target_user_id}`);
    } else if (target_club_id) {
      const { data: profiles } = await supabaseAdmin
        .from("profiles")
        .select("user_id")
        .eq("favorite_club_id", target_club_id);
      userIds = (profiles || []).map((p) => p.user_id);
      console.log(`Targeting club ${target_club_id}: ${userIds.length} fans`);
    } else {
      const { data: roles } = await supabaseAdmin
        .from("user_roles")
        .select("user_id")
        .eq("role", "user");
      userIds = (roles || []).map((r) => r.user_id);
      console.log(`Broadcasting to ${userIds.length} users`);
    }

    const vapidPublic = Deno.env.get("VAPID_PUBLIC_KEY");
    const vapidPrivate = Deno.env.get("VAPID_PRIVATE_KEY");
    const vapidSubject = Deno.env.get("VAPID_SUBJECT") || "mailto:contato@fanaticamente.com";

    if (!vapidPublic || !vapidPrivate) {
      return new Response(
        JSON.stringify({ success: false, error: "VAPID keys not configured", push_sent: 0, push_failed: 0 }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (userIds.length === 0) {
      return new Response(
        JSON.stringify({ success: true, push_sent: 0, push_failed: 0, pwa_subscribers: 0 }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { data: subs } = await supabaseAdmin
      .from("push_subscriptions")
      .select("*")
      .in("user_id", userIds);

    const subsCount = subs?.length ?? 0;
    console.log(`Found ${subsCount} PWA push subscriptions for ${userIds.length} target user(s)`);

    let pushSent = 0;
    let pushFailed = 0;

    if (subs && subs.length > 0) {
      const pushPayload = JSON.stringify({
        title,
        body: message,
        icon: icon || "/pwa-192x192.png",
        badge: "/pwa-192x192.png",
        data: { url: link || "/" },
      });

      const expiredEndpoints: string[] = [];

      const results = await Promise.allSettled(
        subs.map(async (sub) => {
          try {
            const result = await sendWebPush(
              { endpoint: sub.endpoint, p256dh: sub.p256dh, auth: sub.auth },
              pushPayload,
              vapidPublic,
              vapidPrivate,
              vapidSubject
            );
            console.log(`Push to ${sub.endpoint.substring(0, 50)}... status: ${result.status} body: ${result.body}`);
            return result;
          } catch (e: unknown) {
            const msg = e instanceof Error ? e.message : String(e);
            console.error(`Push failed for user ${sub.user_id}:`, msg);
            return { ok: false, status: 0, body: msg };
          }
        })
      );

      results.forEach((result, idx) => {
        if (result.status === "fulfilled") {
          if (result.value.ok) {
            pushSent++;
          } else {
            pushFailed++;
            if (result.value.status === 410) expiredEndpoints.push(subs[idx].endpoint);
          }
        } else {
          pushFailed++;
        }
      });

      if (expiredEndpoints.length > 0) {
        await supabaseAdmin
          .from("push_subscriptions")
          .delete()
          .in("endpoint", expiredEndpoints);
        console.log(`Removed ${expiredEndpoints.length} expired push subscriptions`);
      }
    }

    // Log notification (non-blocking)
    supabaseAdmin.from("notification_logs").insert({
      title,
      message,
      type,
      link: link || null,
      target: target_user_id ? "user" : target_club_id ? "club" : "all",
      target_user_id: target_user_id || null,
      push_sent: pushSent,
      push_failed: pushFailed,
      in_app_sent: 0,
      sent_by: userId,
    }).then(() => {}).catch(console.error);

    return new Response(
      JSON.stringify({
        success: true,
        push_sent: pushSent,
        push_failed: pushFailed,
        pwa_subscribers: subsCount,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    console.error("Error:", e);
    return new Response(JSON.stringify({ error: String(e) }), { status: 500, headers: corsHeaders });
  }
});
